theme: jekyll-theme-minimal
title: Annotation guidelines for pharmacokinetic document classification
description: This website stores the guidelines shared across all the annotators while labelling pharmacokinetic papers
